name: build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Clean Build
        run: ./gradlew clean build
      - name: Determine release status
        if: ${{ runner.os == 'Linux' }}
        run: |
          version=$(./gradlew properties | awk '/^version:/ { print $2; }')
          echo "VERSION=$version" >> $GITHUB_ENV
          if [ "$(echo $version | grep '\-SNAPSHOT')" ]; then
            echo "STATUS=snapshot" >> $GITHUB_ENV
          else
            echo "STATUS=release" >> $GITHUB_ENV
          fi
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          path: ./Bukkit/build/libs/plotsquared-bukkit-${{ env.VERSION }}.jar
